#!/bin/bash

poetry install
if [ $? -ne 0 ]; then
  echo "Poetry installation failed. Please check the error message above."
  exit 1
fi

poetry run ruff check --fix .
if [ $? -ne 0 ]; then
  echo "Some linting errors could not be fixed automatically. Please review and fix them."
  exit 1
fi

poetry run ruff format .
if [ $? -ne 0 ]; then
  echo "Formatting issues found and fixed by Ruff. Please stage the changes."
  exit 1
fi

poetry run mypy
if [ $? -ne 0 ]; then
  echo "Found errors in type checking. Please review the error messages above."
  exit 1
fi
