name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9.22, 3.10.17, 3.11.12, 3.12.6, 3.13.2]
    env:
        CONTAINER_NAME: pymorphic-${{ matrix.python-version }}
        IMAGE_NAME: sreea1408/pymorphic:0.1.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull Docker image
        run: |
          docker pull $IMAGE_NAME

      - name: Start the container in the background
        run: |
          docker run -d --name $CONTAINER_NAME -v $GITHUB_WORKSPACE:/workspace -w /workspace $IMAGE_NAME tail -f /dev/null

      - name: Set up Python and install dependencies
        run: |
          docker exec $CONTAINER_NAME bash -c "pyenv global ${{ matrix.python-version }} && pyenv rehash && poetry install"

      - name: Run Ruff formatting
        if: ${{ matrix.python-version == '3.9.22' }}
        run: |
          docker exec $CONTAINER_NAME bash -c "poetry run ruff format --check"

      - name: Run Ruff linting
        if: ${{ matrix.python-version == '3.9.22' }}
        run: |
          docker exec $CONTAINER_NAME bash -c "poetry run ruff check"

      - name: Run mypy
        if: ${{ matrix.python-version == '3.9.22' }}
        run: |
          docker exec $CONTAINER_NAME bash -c "poetry run mypy ."

      - name: Run tests
        run: |
          docker exec $CONTAINER_NAME bash -c "poetry run pytest"

      - name: Stop and remove the container
        if: always()
        run: |
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
